version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POLL_INTERVAL_MS=300000
      - DB_PATH=/app/data/megasena.db
      - SMTP_HOST=host.docker.internal
      - SMTP_PORT=25
      - SMTP_TLS_REJECT_UNAUTHORIZED=false
      # - SMTP_IGNORE_TLS=true
      - FROM_DOMAIN=bru.to
    volumes:
      - megasena-data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  megasena-data:
